route:
  enabled: true
  host: argonaut.apps.baloise.dev
backend:
  replicaCount: 1
  appPort: 8080
  livenessProbePath: api/actuator/health
  readinessProbePath: api/actuator/health
  image:
    repository: baloiseincubator/argonaut
    tag: feat-initial_pr_decoration-79ff0691a080835d438a0c460d1fb21820016c84
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
  route:
    enabled: true
    path: /
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
