route:
  enabled: true
  host: argonaut.apps.baloise.dev
backend:
  replicaCount: 3
  appPort: 8080
  livenessProbePath: api/actuator/health
  readinessProbePath: api/actuator/health
  image:
    repository: baloiseincubator/argonaut
    tag: feat-initial_pr_decoration-fa3b4db1696615d16c849f1fc7c78d1655046aa3
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
  route:
    enabled: true
    path: /
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
