route:
  enabled: true
  host: argonaut.apps.baloise.dev
backend:
  replicaCount: 3
  appPort: 8080
  livenessProbePath: api/actuator/health
  readinessProbePath: api/actuator/health
  image:
    repository: baloiseincubator/argonaut
    tag: feat-initial_pr_decoration-435667eec6aa120b84eabbea897adc7ec9249c2a-77.1
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
  route:
    enabled: true
    path: /
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
