route:
  enabled: true
  host: "argonaut.apps.baloise.dev"
backend:
  replicaCount: 1
  appPort: 8080
  livenessProbePath: api/actuator/health
  readinessProbePath: api/actuator/health
  image:
    repository: baloiseincubator/argonaut
    tag: feat-pr_github-83694aedf930978e028006e9e9b0b1a855cf6044-45.1
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
  route:
    enabled: true
    path: /
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
