route:
  enabled: true
  host: argonaut.apps.baloise.dev
backend:
  replicaCount: 1
  appPort: 8080
  livenessProbePath: api/actuator/health
  readinessProbePath: api/actuator/health
  image:
    repository: baloiseincubator/argonaut
    tag: feat-pr_creation-623c503b01b2f57eb36def56eb4de54e86952abe
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
  route:
    enabled: true
    path: /
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
